nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'POST', 'OPTIONS']
        allow_headers: ['X-API-KEY', 'Origin', 'X-Requested-With', 'Content-Type', 'Accept', 'Access-Control-Request-Method']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': ~
